name: gprgnn
channels:
  - pytorch
  - defaults
  - conda-forge
  - pyg
dependencies:
  - python=3.8
  - numpy
  - pytorch
  - pytorch-sparse
  - black
  - pylint
  - ca-certificates
  - certifi
  - openssl
  - pip
  - pip:
    - autopep8
    - tqdm
    - torch-geometric
    - matplotlib